iDo I love you? My god, if your love were a grain of sand, mine would be a universe of beaches.
mport random
import pyautogui
import time
a=['I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.','You know you’re in love when you can’t fall asleep because reality is finally better than your dreams','Love is that condition in which the happiness of another person is essential to your own.','The best thing to hold onto in life is each other.','I need you like a heart needs a beat.','I am who I am because of you. You are every reason, every hope, and every dream I’ve ever had.','If I had a flower for every time I thought of you… I could walk through my garden forever.','Take my hand, take my whole life too. For I can’t help falling in love with you','If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.','You’re the closest to heaven, that I’ll ever be.','You are the finest, loveliest, tenderest, and most beautiful person I have ever known and even that is an understatement.','I will never stop trying. Because when you find the one… you never give up.','It’s always better when we’re together.','I love you for all that you are, all that you have been and all that you will be',
'I wasn’t expecting you. I didn’t think that we would end up together. The single most extraordinary thing I’ve ever done with my life is fall in love with you. I’ve never been seen so completely, loved so passionately and protected so fiercely',
'To the world you may be one person, but to one person you are the world.','I’ve tried so many times to think of a new way to say it, and it’s still I love you.','When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible','I love you and that’s the beginning and end of everything.',
'If I know what love is, it is because of you','My soul and your soul are forever tangled.','I love you more than I have ever found a way to say to you.',
'I have found the one whom my soul loves.','Sometimes all you need is a hug from the right person and all your stress will melt away.','In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine','Love is when you sit beside someone doing nothing, yet you feel perfectly happy','He’s more myself than I am. Whatever our souls are made of, his and mine are the same','You are, and always have been, my dream.','I love that you are the last person I want to talk to before I go to sleep at night','Love is composed of a single soul inhabiting two bodies.','What is love? It is the morning and the evening star.','If you find someone you love in your life, then hang on to that love.',
'Come near now, and kiss me.','I need you like a heart needs a beat.','Our love is like the wind. I can’t see it, but I can feel it.','It’s always better when we’re together.','I would rather spend one lifetime with you, than face all the ages of this world alone.','My love for you has no depth, its boundaries are ever-expanding.','When I see your face, there’s not a thing that I would change, ’cause you’re amazing – just the way you are.','Because of you, I can feel myself slowly, but surely, becoming the me I have always dreamed of being.','We loved with a love that was more than love','True love is rare, and it’s the only thing that gives life real meaning.','I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more','I am my beloved’s and my beloved is mine','And in her smile I see something more beautiful than the stars.','It was love at first sight, at last sight, at ever and ever sight','In real love you want the other person’s good. In romantic love you want the other person.','Love does not consist in gazing at each other, but in looking outward together in the same direction',
'You’re always the first and the last thing on this heart of mine. No matter where I go, or what I do, I’m thinking of you','When I saw you I fell in love, and you smiled because you knew.','True love is putting someone else before yourself.','If I had to choose between breathing and loving you I would use my last breath to tell you I love you.','All that you are is all that I’ll ever need','I love being one half of a romantic couple','I love you. You… you complete me.','The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.','You don’t marry someone you can live with — you marry someone you cannot live without','Love is being stupid together.','Romance is the glamour which turns the dust of everyday life into a golden haze.','When I look into your eyes, I know I have found the mirror of my soul.','You know it’s true. Everything I do, I do it for you',
'Life is not the amount of breaths you take, it’s the moments that take your breath away','You’re nothing short of my everything','I am in you and you in me, mutual in divine love.','Love is like the wind, you can’t see it but you can feel it','The day my life changed forever… The day I first saw you.','When you look at me, when you think of me, I am in paradise.','Love doesn’t make the world go ’round. Love is what makes the ride worthwhile.'
,'It was a million tiny little things that, when you added them all up, they meant we were supposed to be together… and I knew it.','Cause all of me loves all of you. Love your curves and all your edges. All your perfect imperfections. Give your all to me. I’ll give my all to you. You’re my end and my beginning.','Each day I love you more, today more than yesterday and less than tomorrow.','There is a madness in loving you, a lack of reason that makes it feel so flawless.','Do I love you? My god, if your love were a grain of sand, mine would be a universe of beaches.','You should be kissed and often, and by someone who knows how.','To love and be loved is to feel the sun from both sides.']
for i in range(0,3):
    time.sleep(3)
    p=random.choice(a)
    pyautogui.typewrite(p)
    pyautogui.press("enter")